USE Fundoo;
GO

CREATE TABLE Collaborators
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    NoteId NVARCHAR(50) NOT NULL,
    OwnerUserId INT NOT NULL,
    CollaboratorUserId INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

SELECT * FROM Collaborators;
GO
